name: Sign Release

on:
  push:
   tags:
   - '[0-9]+.[0-9]+.[0-9]+'
   - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
  workflow_dispatch:
    inputs:
      version:
        description: Version to use in place of a tag

jobs:
  build:
    strategy:
      fail-fast: true
    runs-on: macos-11
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure Signing
      uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        p12-password: ${{ secrets.P12_PASSWORD }}

    - name: Xcode Select
      uses: devbotsxyz/xcode-select@v1.1.0
      with:
        version: latest

    - name: Generate Metadata
      id: metadata
      run: |
        [[ "$GITHUB_REF" =~ refs/tags ]] && VERSION=${GITHUB_REF/refs\/tags\//} || VERSION=${github.event.inputs.version}
        echo ::set-output name=version::${VERSION}
        echo ::set-output name=archive_name::xchtmlreport-${VERSION}.zip

    - name: Build
      run: swift build -v -c release
      
    - name: Sign
      run: |
        codesign --verbose --verify --options=runtime -f -s "Developer ID Application: Tyler Vick (${{ secrets.AC_TEAM_ID }})" .build/x86_64-apple-macosx/release/xchtmlreport
    
    - name: Verify
      run: |
        codesign -vvv --deep --strict .build/x86_64-apple-macosx/release/xchtmlreport

    - name: Package
      run: |
        ditto -c -k --keepParent ".build/x86_64-apple-macosx/release/xchtmlreport" ${{ steps.metadata.outputs.archive_name }}

    - name: Notarize
      run: |
        xcrun notarytool submit ${{ steps.metadata.outputs.archive_name }} --apple-id ${{ secrets.AC_USERNAME }} --password ${{ secrets.AC_PASSWORD }} --team-id ${{ secrets.AC_TEAM_ID }} --wait

    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: application
        path: ${{ steps.get_version.outputs.archive_name }}

  release:
    runs-on: macos-11
    
    needs: build
    
    steps:
    - name: Download
      uses: actions/download-artifact@v2
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: ${{ contains(github.ref, '-') }}
        files: |
          application/xchtmlreport-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
