name: Brew Bump

on:
  workflow_dispatch:
    inputs:
      version:
        type: text
        required: true
        description: "Release tag to use. e.g. refs/tags/2.2.4"

jobs:
  update_brew_formula:
    runs-on: ubuntu-latest

    steps:
#    - name: Update Homebrew tap
#      uses: dawidd6/action-homebrew-bump-formula@v3
#      with:
#        token: ${{ secrets.HOMEBREW_BUMP_ACCESS_TOKEN }}
#        org: XCTestHTMLReport
#        tap: XCTestHTMLReport/homebrew-xchtmlreport
#        formula: xchtmlreport
#        tag: ${{ github.event.inputs.version }}        

    - name: Update Official Homebrew formula
      uses: dawidd6/action-homebrew-bump-formula@v3
      with:
        token: ${{ secrets.HOMEBREW_BUMP_ACCESS_TOKEN }}
        org: XCTestHTMLReport
        formula: xctesthtmlreport
        tag: ${{ github.event.inputs.version }}
